---
title: "why you should care about reproducibility"
description: "Two famous economists, a PhD student, and an Excel spreadsheet: the methodological errors that led to austerity measures taking hold in the UK."
author:
  - name: Helen Arnold
date: Jan 04, 2021
categories:
  - economics
  - intro
creative_commons: CC BY
output:
  distill::distill_article:
    self_contained: false 
    code_folding: true
---

***POST BENG DRAFTED - TEST POST

In January 2010, an economics paper took the world by storm.

This paper, authored by renowned economists Carmen Reinhart and Ken Rogoff, explored the relationship between debt and economic growth.^[Reinhart CM, Rogoff KS. Growth in a Time of Debt. American Economic Review. 2010;100(2):573-8. doi: 10.1257/aer.100.2.573] A key finding was that developed economies had a fiscal cliff: when government debt exceeded 90 per cent of GDP, economic growth suffered.^[Reinhart CM, Rogoff KS. Growth in a Time of Debt. American Economic Review. 2010;100(2):573-8. doi: 10.1257/aer.100.2.573] Right-wing governments embraced this findings to justify austerity measures targeted at reducing public debt^[Inman P. Rogoff and Reinhart defend their numbers: The Guardian; 18 April 2013 (accessed 10 November 2020). Available from: https://www.theguardian.com/business/economics-blog/2013/apr/17/rogoff-reinhart-defend-debt-study] ^[Krugman P. The case for cuts was a lie. Why does Britain still believe it? - The austerity delusion: The Guardian; 29 April 2015 (accessed 10 November 2020). Available from: https://www.theguardian.com/business/ng-interactive/2015/apr/29/the-austerity-delusion] in the global aftermath of the collapse of the US banking sector in 2007-08.

But when PhD student Thomas Herndon set out to replicate the findings of Reinhart and Rogoff in a graduate class assignment two years later, he found major flaws. Not only were there formula errors in the Excel spreadsheet used by Reinhart and Rogoff, but questionable weightings had been applied to the countries in the analysis. (4-6) Once these issues were corrected, the fiscal cliff vanished. (3-6) In addition, questions were raised about the causal direction of the relationship – rather than high debt causing slow growth, economists began to question whether it was instead slow growth that caused high debt. (3)

Herndon’s debunking research, published in 2013, coincided with most developed countries beginning to abandon austerity. (3) However, despite increasing evidence that austerity was not an economic silver bullet, (3) the UK government has held firmly to austerity measures such as cuts to welfare payments and social services since 2010, citing Greece as an example of an economy in crisis. (3, 7) Recent criticism has focused heavily on increases in poverty, food shortages and crime in the UK under austerity measures. (7)

The Reinhart and Rogoff controversy highlighted three major problems in the relationship between science and politics: first, that a single paper could be used to justify broad-reaching government responses to major social crises; second, that even after major flaws with this paper were discovered, governments continued to argue that the austerity approach to managing debt was supported by evidence; and third, that people re-elected a government committed to policy based on long-discredited research.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
